### ISSUE TITLE
First Step

### ISSUE THREAD

**Issue by fetburner** [fetburner/Udon#1]
とりあえず最初はこのぐらいの簡単な言語のparser, lexerを実装する事を目標に遊んでいきたいですね
![dsc_0203](https://cloud.githubusercontent.com/assets/2970249/7730108/51d77d0c-ff53-11e4-87ba-f301c0f5c85c.jpg)

**Comment by nomaddo** [comment]
プロ演Bの講義資料
http://www.kb.ecei.tohoku.ac.jp/~sumii/class/proenb2013/myc/

cmファイルの書き方
http://www.smlnj.org/doc/CM/new.pdf

ML-Yacc user manual
http://www.smlnj.org/doc/ML-Yacc/

SSA_and_CPS 講義資料
http://sites.fas.harvard.edu/~lib153/lectures/SSA_and_CPS.pdf

A Correspondence between Continuation Passing Style
and Static Single Assignment Form
https://www.cs.purdue.edu/homes/suresh/502-Fall2008/papers/kelsey-ssa-cps.pdf

LLVMのチュートリアルたち
http://www.ibm.com/developerworks/jp/opensource/library/os-createcompilerllvm1/
http://www.slideshare.net/herumi/llvm-17911004

**Comment by fetburner** [comment]
議事録のようなもの
![dsc_0197](https://cloud.githubusercontent.com/assets/2970249/7771030/417083aa-00cf-11e5-82f2-d9a945764ac1.jpg)

**Comment by fetburner** [comment]
The Essence of Compiling with Continuations
https://users.soe.ucsc.edu/~cormac/papers/pldi93.pdf

**Comment by nomaddo** [comment]
A First-Order One-Pass CPS Transformation
http://www.brics.dk/RS/01/49/BRICS-RS-01-49.pdf

Compiling with Continuations, Continued
http://research.microsoft.com/pubs/64044/compilingwithcontinuationscontinued.pdf

Compiling with continuations (講義資料？)
http://www.cs.cornell.edu/courses/cs6110/2013sp/lectures/lec16-sp13.pdf

Reading papers on CPS, SSA, ANF and the likes
http://gallium.inria.fr/blog/ssa-cps-reading-notes/

Efficient Compilation of Tail Calls and Continuations to JavaScript
http://users-cs.au.dk/danvy/sfp12/papers/thivierge-feeley-paper-sfp12.pdf

An introduction to Continuation Passing Style (CPS) by Ramakrishnan Muthukrishnan
https://www.youtube.com/watch?v=f6G_BO2J94k

CPS to LLVM SSA conversion in literate programming
http://l-lang.blogspot.jp/2012/08/cps-to-llvm-ssa-conversion-in-literate_3067.html

**Comment by fetburner** [comment]
プロ演Bのスライドを参考にレキサとパーサを実装しました。
SML/NJのREPLで
CM.make "./source.cm";
Udon.run ();
を評価すると対象言語のREPLが起動し、式;を入力すると構文解析結果を文字列にしたものが表示されます。
例:
fn x => fn y => x;
(fn x => (fn y => x))
1 2 3;
((1 2) 3)
![15dad73e-s](https://cloud.githubusercontent.com/assets/2970249/7789296/9f9cdce4-0296-11e5-8e91-bfc7014d8c29.gif)
