### ISSUE TITLE
型付けに失敗する

### ISSUE THREAD

**Issue by nomaddo** [fetburner/Udon#4]
下のプログラムの型がつかないですー。

```
let val rec fact = fn n => if op <= (1, n) then 1 else op * (n, fact (op - (n, 1))) in fact 10 end;  
Error : failed to unify int and (int -> 'a)
```

ちなみにsml/njでは普通に型付け通りました。

**Comment by nomaddo** [comment]
```
let val rec f = fn n => f n in f 10 end;
Error : failed to unify 'a and 'a
```

**Comment by nomaddo** [comment]
let val id = fn x => fn x => if x then true else true in id end;
    let val id_14 : (int -> (bool -> bool)) = (fn x_12 : int => (fn x_13 : bool => (if x_13 : bool then true : bool else true : bool) : bool) : (bool -> bool)) : (int -> (bool -> bool)) in id_14 : (int -> (bool -> bool)) end : (int -> (bool -> bool))

**Comment by fetburner** [comment]
直しました
